### ISSUE TITLE
Exception after upgrade to Spring Boot 1.5.1 & Vaadin-spring-boot : 1.2.0

### ISSUE THREAD

**Issue by phrouv** [vaadin/spring#182]
My web app is a Vaadin Spring Boot one.
Vaadin-spring-boot : 1.2.0 & Spring-boot : 1.4.4 is working fine.
When I update spring-boot to 1.5.1 without any change of code, the app deployment fails with the exception : java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/ServletListenerRegistrationBean
A dependency of com.vaadin:vaadin-push:jar:7.7.7 needs to be corrected : com.vaadin.external.atmosphere:atmosphere-runtime:jar:2.2.9.vaadin2 has got a bean 'atmosphereSessionSupport' whose type is still 
org.springframework.boot.context.embedded.ServletListenerRegistrationBean

**Comment by geld0r** [comment]
Can confirm, have the same issue with the same versions.

**Comment by mstahv** [comment]
I tried to reproduce the issue but no luck for me. Could either of you share a reduced example project where this issue can be reproduced?

**Comment by geld0r** [comment]
My "workaround" for this issue was to remove push support for my app.

**Comment by mstahv** [comment]
I tried with push and it worked just fine. If you can find the problematic combination, it would really help to get this sorted out.

**Comment by zxyroy** [comment]
I just reproduce this problem. I think the problem comes from another project called [vaadin4spring](https://github.com/peholmst/vaadin4spring). If you are using vaadin-spring-ext-boot, it cause the problem.
